### ISSUE TITLE
nvidia-smi logic is broken

### ISSUE THREAD

**Issue by alexmherrmann** [responsibleproblemsolving/energy-usage#1]
the `valid_gpu` function checks for `nvidia-smi`, and if `True`, then it will run the command
`nvidia-smi -i 0 --format=csv,noheader --query-gpu=power.draw`. Unfortunately this command can sometimes return `[Not Supported]` if it's not avaiable. This means that evaluate.py:49 breaks as a float is assumed to be returned and `[Not Supported]` obviously can't be converted to a float.

**Comment by klottick** [comment]
Thanks for pointing this out. It should be resolved now here and in the new pip install.
