### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by thibaudcolas** [responsibleproblemsolving/energy-usage#16]
I tried to run this package on macOS and Ubuntu (GitHub Actions, no idea what hardware is underneath), and got the following error:

```
ERROR:root:
Traceback (most recent call last):
  File "benchmark.py", line 115, in <module>
    energyusage.evaluate(energy_usage_run, pdf=True)
  File "venv/lib/python3.8/site-packages/energyusage/evaluate.py", line 338, in evaluate
    utils.log("The energy-usage package only works on Linux kernels "
  File "venv/lib/python3.8/site-packages/energyusage/utils.py", line 203, in log
    measurement = args[1]
IndexError: tuple index out of range
```

This is a bit confusing because at first I thought the issue was just "The energy-usage package only works on Linux kernels ", and didn’t know there were more specific requirements. Looking into the code further, this breaks because the `log` util has logic to check for specific keywords in the log messages:

https://github.com/responsibleproblemsolving/energy-usage/blob/eb26f34611fc7b9b64d412386ff655004ed7121a/energyusage/utils.py#L197-L200

This will incorrectly match "GPU" in the "no support" warning, and as such make the error very confusing: https://github.com/responsibleproblemsolving/energy-usage/blob/eb26f34611fc7b9b64d412386ff655004ed7121a/energyusage/evaluate.py#L398-L401

**Comment by sorelle** [comment]
Sorry for the slow response to this... we've mostly stopped supporting this package and have moved much of the functionality over to https://github.com/mlco2/codecarbon (along with additional functionality).

**Comment by thibaudcolas** [comment]
Good to know :) I was told about this project yesterday in a conference talk (https://www.thegreenwebfoundation.org/djangocon-eu-2021/), so it would be nice for you to update the README with a prominent link to CodeCarbon.

**Comment by sorelle** [comment]
Oh wow - didn't know anyone was still pointing to this.  Thanks!  Readme updated.
